sudo: required
services:
  - docker

before_install:
  - docker build -t lulunicole/docker-react -f Dockerfile.dev .

script:
  - docker run lulunicole/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-107597345660"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
